name: .Net Build MapItEasy

on:
  push:
    paths: 
      - 'src/MapItEasy/**'
  pull_request:
    paths: 
      - 'src/MapItEasy/**'
  workflow_dispatch:
  
jobs:
  build:

    defaults: 
      run:
        working-directory: src/MapItEasy
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.100

    - name: Test
      run: dotnet test MapItEasy.Tests/MapItEasy.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

    - name: Build
      run: dotnet build --configuration Release 

    - name: Upload MapItEasy
      uses: actions/upload-artifact@v4
      with:
        name: MapItEasy
        path: src/MapItEasy/MapItEasy/bin/Release/*.nupkg

    - name: Upload MapItEasy.Generators
      uses: actions/upload-artifact@v4
      with:
        name: MapItEasy.Generators
        path: src/MapItEasy.Generators/bin/Release/*.nupkg
        
    - name: Publish MapItEasy to NuGet
      if: startsWith(github.ref, 'refs/tags/releases/v')
      run: |
        dotnet nuget push "MapItEasy/bin/Release/*.nupkg" \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json \
          --skip-duplicate

    - name: Publish MapItEasy.Generators to NuGet
      if: startsWith(github.ref, 'refs/tags/releases/v')
      run: |
        dotnet nuget push "MapItEasy.Generators/bin/Release/*.nupkg" \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json \
          --skip-duplicate